from pptx import Presentation
from pptx.util import Inches
import os

def build_pptx(title, kpis, insights, images, out_path):
    prs = Presentation()

    # Title slide
    s0 = prs.slides.add_slide(prs.slide_layouts[0])
    s0.shapes.title.text = title

    insights = [point.strip() for point in insights.split("*") if point.strip()]

    # Adding content generated by LLM using calculated perforamnce metrics
    for idx, insight in enumerate(insights, 1):
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = f"Executive Insight "
        tf = slide.shapes.placeholders[1].text_frame
        for line in insight.split("\n"):
            p = tf.add_paragraph()
            p.text = line

    # Adding plots & figures
    for img in images:
        if not os.path.exists(img): continue
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = os.path.basename(img)
        slide.shapes.add_picture(img, Inches(0.5), Inches(1.2), width=Inches(9))

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    prs.save(out_path)
